### ISSUE TITLE
[1.19.2-2.6] Random Crash

### ISSUE THREAD

**Issue by BookerCatch** [Jackiecrazy/footwork#1]
I'm not sure what triggered it. I spawned two piglins and began testing out the combat.

[crash-2023-07-28_23.47.45-server.txt](https://github.com/Jackiecrazy/footwork/files/12206220/crash-2023-07-28_23.47.45-server.txt)

**Comment by Jackiecrazy** [comment]
Update Project: War Dance to the latest version. Sifu was broken in that version.
