### ISSUE TITLE
1.20.1 Bug (or maybe feature request?) With Target Dummy Mod

### ISSUE THREAD

**Issue by Silvertide7** [Jackiecrazy/footwork#2]
I created an issue on Cloak and Dagger but then realized that this API causes the issue even when cloak and dagger isn't installed. The [Target Dummy](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm) mod entity cannot be damaged and the damage numbers / dps text  doesn't show up until you damage it with a projectile or explosion. I'm guessing this gets the target dummy to target you and you can damage it again. Then after 5 seconds you can't damage it anymore I'm guessing that's because it loses aggro from you after that time.

I think if there was a blacklist that you could add entities too that would be ignored from this footwork system that would be great for edge cases like this one. Thanks for the cool mod though!

**Comment by Jackiecrazy** [comment]
That is not how this works. Every system is designed with universality in mind and is inextricably linked with base level mechanics, they cannot be "completely disabled" willy-nilly.

I'll look into the bug.

**Comment by Silvertide7** [comment]
Ah okay gotcha. Awesome thank you for taking a look! I love the implementation and idea of your mod, but giving the players the target dummy for dps testing etc is a must have as well so hoping I can get them to work together correctly.

**Comment by Silvertide7** [comment]
Not sure if this is helpful but heres a little more info. In the mob detection rules config I did add `"dummmmmmy:target_dummy, aeimnopvw"` to the array and that didn't seem to help. Probably because of the target dummy not having targeting mechanics or something?

When approaching the dummy I do see the eye change from closed to open and notice me.

**Comment by Jackiecrazy** [comment]
fixed.
