### ISSUE TITLE
1.20.1 - Footwork causing Slider and Valkyrie Queen from Aether to become immune to player attacks

### ISSUE THREAD

**Issue by Vipibolt** [Jackiecrazy/footwork#4]
I was going to create an issue on [Cloak & Dagger](https://github.com/Jackiecrazy/CloakAndDagger) but similar to the situation of #2, the API here is causing issues with two bosses from the Aether mod, preventing both the Slider and the Valkyrie queen from taking any damage from a player. The Sun Spirit works fine though as his unique gimmick of damaging him remains unaffected.
Using only:
> footwork-4.3
> aether-1.20.1-1.0.0-beta.1.4-neoforge

Hopefully something can be done to fix it.
Example gif below

![itdoesntwork!](https://github.com/Jackiecrazy/footwork/assets/150594814/24c4468f-653e-4e23-af0d-7d27587ad570)

**Comment by Jackiecrazy** [comment]
aha, I see the problem now. Fix uploaded.
